name: Deploy NuGet Package

env:
  PROJECT_PATH: './src/MassTransit.MySqlOutbox/MassTransit.MySqlOutbox.csproj'
  OUTPUT_DIR: 'nupkgs'
  NUGET_SOURCE: 'https://api.nuget.org/v3/index.json'
  NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

on:
  workflow_dispatch:
  push:
    branches:
      - none-yet

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Build
        run: dotnet build ${{ env.PROJECT_PATH }}

      - name: Pack
        run: dotnet pack ${{ env.PROJECT_PATH }} --output ${{ env.OUTPUT_DIR }} 

      - name: Publish
        run: dotnet nuget push ${{ env.OUTPUT_DIR }}/*.nupkg -k ${{ env.NUGET_API_KEY }} -s ${{ env.NUGET_SOURCE }}
